spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/steam_battle_db
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true
steam:
  api-url: ${STEAM_API_URL}
  api-key: ${STEAM_API_KEY}
  steamid: ${MY_STEAM_ID}